baseURL = "https://www.weshargrove.com/"
languageCode = "en-US"
title = "Wes Hargrove Photography - Landscape Photography"

configDir = "config"
contentDir = "content"
layoutDir = "layouts"
publishDir = "build"

rssLimit = 25

[taxonomies]
  gallery = "galleries"
