baseURL = "https://www.weshargrove.com/"
languageCode = "en-US"
title = "Wes Hargrove Photography - Landscape Photography"

contentDir = "content"
layoutDir = "layouts"
publishDir = "build"

rssLimit = 10

[params]
  cdnUrl = "https://cdn.weshargrove-photos.net/"
  MicroBlogUsername = "wes"

[taxonomies]
  gallery = "galleries"
