baseurl = "https://www.weshargrove.com/"
languageCode = "en-US"
title = "Wes Hargrove Photography - Landscape"

contentDir = "content"
layoutDir = "layouts"
publishDir = "build"

[params]
  cdnUrl = "https://cdn.weshargrove.com"
