baseURL = "https://www.weshargrove.com/"
languageCode = "en-US"
title = "Wes Hargrove Photography - Landscape Photography"

contentDir = "content"
layoutDir = "layouts"
publishDir = "build"

[params]
  cdnUrl = "https://weshargrovephoto.blob.core.windows.net/photos/"
  MicroBlogUsername = "wes"

[taxonomies]
  gallery = "galleries"
